[package]
name = "snowflake_me"
version = "0.2.0"
authors = ["houseme <housemecn@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A distributed unique ID generator inspired by Twitter's Snowflake"
homepage = "https://github.com/houseme/snowflake-rs"
repository = "https://github.com/houseme/snowflake-rs"
readme = "README.md"
keywords = ["snowflake", "random", "id", "generator", "uniqueness"]
categories = ["development-tools", "data-structures", "algorithms"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["now"] }
thiserror = "1"
pnet_datalink = { version = "0.35", default-features = false }


[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false

