[package]
name = "snowflake_me"
version = "0.1.8"
authors = ["houseme <housemecn@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A distributed unique ID generator inspired by Twitter's Snowflake"
homepage = "https://github.com/houseme/snowflake-rs"
repository = "https://github.com/houseme/snowflake-rs"
readme = "README.md"
keywords = ["snowflake", "random", "id", "generator", "uniqueness"]
categories = ["development-tools", "data-structures", "algorithms"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
thiserror = "1.0.37"
pnet_datalink = "0.31.0"
time = "0.3.15"
#serde = { version = "1.0", optional = true }
#serde_derive = { version = "1.0", optional = true }

[dev-dependencies]
bencher = "0.1.5"
#time = "0.1"
#uuid = { version = "0.7", features = ["v4"] }
#rand = "0.6"
#threadpool = "1"

[features]
#default=[]

[[bench]]
name = "bench"
harness = false

#serde_support = ["serde", "serde_derive"]